---
- name: Auxiliary Tools
  hosts: offloader
  tags:
    - tmux
    - speedtest
  roles:
    - tools-install

- hosts: offloader
  roles:
    - role: interfaces

- name: install and configure batman
  hosts: offloader
  tags:
    - bat
    - batman
    - batman5
    - batmanv5
    - batman_v5
  roles:
    - batman-install

- name: install and configure fastd
  hosts: offloader
  tags:
    - fastd
  roles:
    - fastd-install

- name: fix dhcp client issues
  hosts: offloader
  tags:
    - dhcp
  roles:
    - dhcpcd
  vars:
    dhcpcd_global_config:
      - keyword: noipv4ll
      - keyword: nogateway
        state: absent
      - keyword: denyinterfaces
        value: "bat* vlan*"
      - keyword: clientid
      - keyword: duid
        state: absent
      - keyword: slaac
        value: hwaddr
    dhcpcd_interface_config:
      - name: "{{ outbound_lan_interface }}"
        config: |
          gateway
          metric 0
      - name: "br-ffbsee"

- name: install alfred-scripts for ffbsee
  hosts: offloader
  tags:
    - alfred
    - printmap
    - print-map
  roles:
    - alfred-install
