---
- name: Install additional tools
  become: yes
  apt:
    pkg:
      - aptitude
      - fsarchiver
      - nano
      - nmap
      - iperf3
      - net-tools
      - speedtest-cli
      - tmux
      - traceroute
      - vlan
      - git
      - bc
      - tshark
      - tcpdump
      - iotop
      - iftop
    state: present
